# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Another Developer Blog"
description: > # this means to ignore newlines until "email:"
   Mais um blog de um desenvolvedor...

email: faria.luiz@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/landscape.jpg"

name: 'Luiz Faria'
author: 'Luiz Faria'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://lfppfaria.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle:

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/lfppfaria
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	 https://www.linkedin.com/in/lfppfaria/
    desc:	Linkedin
#    share_url:
#    share_title:
#    share_link:
